# Generated by Django 3.2.11 on 2022-01-10 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temperature_data', '0002_datainput'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataInput',
        ),
    ]
