# Generated by Django 3.2.11 on 2022-01-11 21:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperature_data', '0004_datainput'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datainput',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
