# Generated by Django 3.2.11 on 2022-01-12 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('temperature_data', '0005_alter_datainput_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datainput',
            name='devices',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='Dispozitive', to='temperature_data.device'),
        ),
    ]
