# Generated by Django 3.2.11 on 2022-01-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperature_data', '0006_alter_datainput_devices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datainput',
            name='devices',
        ),
        migrations.AddField(
            model_name='datainput',
            name='devices',
            field=models.ManyToManyField(to='temperature_data.Device'),
        ),
    ]
