# Generated by Django 3.2.11 on 2022-01-12 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temperature_data', '0008_auto_20220112_1037'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataInput',
        ),
    ]
