# Generated by Django 3.2.11 on 2022-01-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperature_data', '0010_datainput'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datainput',
            name='temp',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
