# Generated by Django 3.2.11 on 2022-01-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperature_data', '0011_alter_datainput_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datainput',
            name='temp',
            field=models.IntegerField(),
        ),
    ]
